name: using context
on: [push, pull_request]
jobs:
    job01:
      runs-on: ubuntu-latest
      steps:
        - name: 1sr step
          run: echo "hello"
        - name: if condition
          if: ${{success()}}
          run: echo "run after 1st step"