name: 1sr-workflow
on: [push]
jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo command
              run: echo "hello world 1"
            - name: npm command
              run: node -v
              
