name: matrix-workflow
on: [push]
jobs:
  job01:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16]
        include:
          - os: ubuntu-latest
            name: ubuntu
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: step01
        run: |
         node -v
         echo ${{toJson(matrix)}}
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
      

