name: caching and artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: debian-latest
    steps: 
      - uses: actions/checkout@v3
      - name: cache dependencs
        id: chache-dep
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "npm-cache"
      - name: opt of cache
        run: echo '${{ toJSON(steps.chache-dep.outputs) }}'
      - name: Install dependencie\
        run: npm install
      - name: run test
        run: npm test
      - name: save the artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-coverage
          path: coverage          
      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
            console.log(res.data)
